# Generated by Django 3.1.1 on 2020-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201211_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
