# Generated by Django 3.1.1 on 2020-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201208_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
