# Generated by Django 3.1.1 on 2020-12-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201208_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='dilivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.address'),
            preserve_default=False,
        ),
    ]
